Core.WebUI/Areas/Author/Controllers/InstructionController.cs
using System.Threading.Tasks;
using AutoMapper;
using Core.BLL.Abstractions.Services;
using Core.BLL.DTO.InstructionDTO;
using Core.DAL.Entities.Domain;
using Core.WebUI.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Core.WebUI.Areas.Author.Controllers
{
    [Authorize(Roles = "Author")]
    [Area("Author")]
    public class InstructionController: Controller
    {
        private readonly IInstructionService _instructionService;

        public InstructionController(IInstructionService instructionService)
        {
            _instructionService = instructionService;
        }

        public async Task<IActionResult> Index()
        {
        
            return View(await _instructionService.GetAllInstructionByAuthorIdAsync(this.User.GetUserId()));
        }
        [HttpGet]
        public ViewResult Create()
        {
            ViewData["Action"] = "Create";
            return View("AddEditInstuction", new InstructionDTO());
        }

        [HttpGet]
        public async Task<ViewResult> Update(int id)
        {
            var instruction = await _instructionService.GetByIdAndAuthorIdAsync(id, this.User.GetUserId());
            ViewData["Action"] = "Edit";
            return View("AddEditInstuction", instruction);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrUpdate(InstructionDTO model)
        {
            var instruction = Mapper.Map<InstructionDTO, Instruction>(model);
            instruction.AuthorId = this.User.GetUserId();
            await _instructionService.AddOrUpdateAsync(instruction);
            return RedirectToAction("Index");
        }

        
        public async Task<IActionResult> Delete(int id)
        {            
            await _instructionService.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

Core.WebUI/Controllers/InstructionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core.BLL.Abstractions.Services;
using Microsoft.AspNetCore.Mvc;

namespace Core.WebUI.Controllers
{
    public class InstructionsController : Controller
    {

        private readonly IInstructionService _instructionService;

        public InstructionsController(IInstructionService instructionService)
        {
            _instructionService = instructionService;
        }
        public IActionResult Index()
        {
            return View(_instructionService.GetAllInstructions());
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(_instructionService.GetAllInstructions());
        }


        [HttpPost]
        public IActionResult AddOrUpdate()
        {
            return View(_instructionService.GetAllInstructions());
        }
    }
}

Core.WebUI/Views/Instructions/View.cshtml
@model Core.DAL.Entities.Domain.Instruction

@{
    ViewData["Title"] = "View";
}

<h2>View</h2>

<h4>Instruction</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Instructions" asp-action="AddOrUpdate">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedTime" class="control-label"></label>
                <input asp-for="CreatedTime" class="form-control" />
                <span asp-validation-for="CreatedTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastUpdate" class="control-label"></label>
                <input asp-for="LastUpdate" class="form-control" />
                <span asp-validation-for="LastUpdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}