Core.WebUI/Areas/Author/Controllers/InstructionController.cs
using System.Threading.Tasks;
using AutoMapper;
using Core.BLL.Abstractions.Services;
using Core.BLL.DTO.InstructionDTO;
using Core.DAL.Entities.Domain;
using Core.WebUI.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Core.WebUI.Areas.Author.Controllers
{
    [Authorize(Roles = "Author")]
    [Area("Author")]
    public class InstructionController: Controller
    {
        private readonly IInstructionService _instructionService;

        public InstructionController(IInstructionService instructionService)
        {
            _instructionService = instructionService;
        }

        public async Task<IActionResult> Index()
        {
        
            return View(await _instructionService.GetAllInstructionByAuthorIdAsync(this.User.GetUserId()));
        }
        [HttpGet]
        public ViewResult Create()
        {
            ViewData["Action"] = "Create";
            return View("AddEditInstuction", new InstructionDTO());
        }

        [HttpGet]
        public async Task<ViewResult> Update(int id)
        {
            var instruction = await _instructionService.GetByIdAndAuthorIdAsync(id, this.User.GetUserId());
            ViewData["Action"] = "Edit";
            return View("AddEditInstuction", instruction);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrUpdate(InstructionDTO model)
        {
            var instruction = Mapper.Map<InstructionDTO, Instruction>(model);
            instruction.AuthorId = this.User.GetUserId();
            await _instructionService.AddOrUpdateAsync(instruction);
            return RedirectToAction("Index");
        }

        
        public async Task<IActionResult> Delete(int id)
        {            
            await _instructionService.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

Core.WebUI/Controllers/InstructionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core.BLL.Abstractions.Services;
using Microsoft.AspNetCore.Mvc;

namespace Core.WebUI.Controllers
{
    public class InstructionsController : Controller
    {

        private readonly IInstructionService _instructionService;

        public InstructionsController(IInstructionService instructionService)
        {
            _instructionService = instructionService;
        }
        public IActionResult Index()
        {
            return View(_instructionService.GetAllInstructions());
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(_instructionService.GetAllInstructions());
        }


        [HttpPost]
        public IActionResult AddOrUpdate()
        {
            return View(_instructionService.GetAllInstructions());
        }
    }
}

Core.WebUI/Areas/Author/Views/Instruction/AddEditInstuction.cshtml
@model Core.BLL.DTO.InstructionDTO.InstructionDTO

@{
    ViewData["Title"] = $"{ViewData["Action"]} Instruction";
    Layout = "_EditorLayout";
}

<div class="row">
    <div class="card col-12">
        <div class="card-header">
            <h1>@ViewData["Action"] Instruction</h1> 
        </div>
        <div class="card-body">
            <div class="col-md-12">
                <form asp-controller="Instruction" asp-action="AddOrUpdate" method="post" >
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <input type="hidden" name="id" value="@Model.Id"/>
                    <div class="row">
                        <div class=" col-md-12 col-12">
                            <div class="form-group bmd-form-group">
                                <label asp-for="Title"></label>
                                <input asp-for="Title" class="form-control" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class=" col-md-12 col-xs-12">
                            <div class="form-group bmd-form-group">
                                <label asp-for="Summary"></label>
                                <textarea asp-for="Summary" class="form-control"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class=" col-12">
                            <div class="form-group bmd-form-group">
                                <label asp-for="Content"></label>
                                <textarea asp-for="Content" class="form-control"></textarea>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-default">@ViewData["Action"]</button>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/js/tinyMCEPack.min.js"></script>
    <script>tinymce.init(
    {
        selector: "#Content",
        skin_url: "@Url.Content("~/css/TinyMCEPack/")",
        content_css:"@Url.Content("~/css/site.css")",
        theme: "modern",
        plugins: [
            'advlist autolink link image imagetools lists charmap print preview hr anchor pagebreak spellchecker',
            'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
            'save table contextmenu directionality emoticons template paste textcolor'
        ],
        height: 900,
        plugin_preview_width: 1200,
        toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media fullpage | forecolor backcolor emoticons'
        
    });</script>
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Core.WebUI/Areas/Author/Views/Instruction/Index.cshtml
@model List<Core.BLL.DTO.InstructionDTO.InstructionSummaryDTO>

@{
    ViewBag.Title = "title";
    Layout = "_EditorLayout";
}
@{
    ViewData["Title"] = "View";
}

<h1>Your articles</h1> 
<a  class="btn btn-secondary" asp-controller="Instruction" asp-action="Create">Create</a>
<table class="table table-striped">
    <thead>
    <tr>
        <th>#</th>
        <th>Title</th>
        <th>Summary</th>
        <th>Created Time</th>
        <th>Last Update</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var temp in Model.Select((instruction,index)=>new {instruction = instruction, index = index}))
    {
        <tr>
            <th scope="row">@temp.instruction.Id</th>
            <td>@temp.instruction.Title</td>
            <td>@temp.instruction.Summary</td>
            <td>@temp.instruction.CreatedTime</td>
            <td>@temp.instruction.LastUpdate</td>
            <td>
                <div class="btn-group">
                    <button class="btn bmd-btn-icon dropdown-toggle" type="button" id="@($"ex{temp.index}")" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">more_vert</i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-left" aria-labelledby="@($"ex{temp.index}")">
                        <a class="dropdown-item" asp-controller="Instruction" asp-action="Update" asp-route-id="@temp.instruction.Id">Update</a>
                        <a class="dropdown-item" data-toggle="modal" data-link="@Url.Content($"/instruction/delete?id={@temp.instruction.Id}")" data-target="#deleteModal">
                            Delete
                        </a>
                    </div>

                </div>
            </td>
        </tr>
    }
    </tbody>
</table>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
              Are you really want to delete this item?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a role="link" class="btn btn-primary">Yes</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $('#deleteModal').on('show.bs.modal', function (e) {

            //get data-id attribute of the clicked element
            var link = $(e.relatedTarget).data('link');

            //populate the textbox
            $(e.currentTarget).find('a[role="link"]').attr("href", link);
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}